# This workflow runs the tests for each  microservice
name: tests-payments

# on any pull request
on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    env:
      STRIPE_KEY: ${{secrets.STRIPE_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: cd payments && npm install && npm run test:ci
