# This workflow runs the tests for each  microservice
name: tests-tickts

# on any pull request
on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    env:
      STRIPE_KEY: ${{secrets.STRIPE_KEY}}
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
